"use client"

import { useI18n } from "@/lib/i18n"

const content = {
  en: {
    title: "Terms of Service",
    lastModified: "Last modified: March 17, 2025",
    intro: `Please read these Terms of Service ("Terms") carefully before using Sakura AI (the "Service") operated by Sakura AI ("Company", "we", "us", or "our"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. By accessing or using the Service you agree to be bound by these Terms.`,
    sections: [
      {
        title: "1. Definitions",
        items: [
          { label: "Service", text: "The Sakura AI website and API." },
          { label: "User / You", text: "Any individual or entity accessing or using the Service." },
          { label: "Account", text: "A unique account created for you to access the Service." },
          { label: "Credits", text: "The in-Service currency used to generate images. Each image generation costs 50 credits. Free users receive 100 credits per day." },
          { label: "Content", text: "Text prompts, images, or other material you submit to the Service." },
          { label: "Privacy Policy", text: "Our Privacy Policy available at /privacy." },
          { label: "Terms", text: "These Terms of Service available at /terms." },
        ],
      },
      {
        title: "2. Accounts",
        text: "To use certain features of the Service, you must sign in with a Google account. You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts, refuse service, or remove content at our sole discretion.",
      },
      {
        title: "3. Technical Requirements",
        intro: "To use the Service, your device must:",
        items: [
          "Support one of the following browsers: Chrome, Opera, Firefox, Safari, or Microsoft Edge (latest stable version recommended).",
          "Have JavaScript enabled.",
          "Have a stable internet connection.",
        ],
      },
      {
        title: "4. Credits and Billing",
        subsections: [
          { title: "4.1 Free Credits", text: "Each registered user receives 100 free credits per day, which reset at midnight UTC. Unused free credits do not roll over to the next day." },
          { title: "4.2 Paid Credits", text: "You may purchase additional credits via PayPal. Paid credits do not expire and are consumed after free credits are exhausted. All purchases are final unless otherwise required by applicable law." },
          { title: "4.3 Payment", text: "Payments are processed by PayPal. You must provide accurate and complete billing information. By submitting payment information, you authorize us to charge the applicable fees. We reserve the right to refuse or cancel orders at any time for reasons including service availability, pricing errors, or suspected fraud." },
          { title: "4.4 Taxes", text: "The Company is not responsible for any additional fees or taxes imposed by the relevant authorities of the country in which you reside. Payment of such fees remains your responsibility." },
        ],
      },
      {
        title: "5. Acceptable Use",
        intro: "You agree not to use the Service to:",
        items: [
          "Generate content that is illegal, harmful, threatening, abusive, or defamatory.",
          "Generate sexually explicit content involving minors.",
          "Infringe any intellectual property rights of third parties.",
          "Attempt to reverse-engineer, scrape, or abuse the API.",
          "Circumvent rate limits or credit systems.",
          "Use the Service for any unlawful purpose.",
        ],
        outro: "We reserve the right to suspend or terminate your access if you violate these rules.",
      },
      {
        title: "6. Content",
        text: `You retain ownership of any Content you submit to the Service. By submitting Content, you grant us a limited, non-exclusive, royalty-free license to process and transmit your Content solely to provide the Service.\n\nYou represent and warrant that: (i) you own or have the right to use the Content you submit, and (ii) your Content does not violate the privacy rights, publicity rights, copyrights, or any other rights of any person or entity.\n\nWe take no responsibility and assume no liability for Content you or any third party submits through the Service.`,
      },
      {
        title: "7. AI-Generated Images",
        text: `Images generated by the Service are produced by third-party AI models (currently Google Gemini via OpenRouter). We do not guarantee the accuracy, quality, or fitness for any particular purpose of generated images.\n\nOwnership and licensing of AI-generated images may vary by jurisdiction. You are solely responsible for ensuring your use of generated images complies with applicable laws.`,
      },
      {
        title: "8. Intellectual Property",
        text: "The Service and its original content (excluding Content submitted by users), features, and functionality are and will remain the exclusive property of Sakura AI and its licensors. Our trademarks may not be used in connection with any product or service without our prior written consent.",
      },
      {
        title: "9. Disclaimer of Warranties",
        text: 'THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.',
      },
      {
        title: "10. Limitation of Liability",
        text: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SAKURA AI, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR ACCESS TO OR USE OF (OR INABILITY TO ACCESS OR USE) THE SERVICE.",
      },
      {
        title: "11. Termination",
        text: "We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Service will immediately cease. Unused paid credits are non-refundable upon termination for cause.",
      },
      {
        title: "12. Governing Law",
        text: "These Terms shall be governed and construed in accordance with applicable law, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved through binding arbitration or in the courts of competent jurisdiction.",
      },
      {
        title: "13. Changes to Terms",
        text: 'We reserve the right to modify or replace these Terms at any time. We will provide notice of significant changes by updating the "Last modified" date. Your continued use of the Service after any changes constitutes your acceptance of the new Terms.',
      },
      {
        title: "14. Contact Us",
        intro: "If you have any questions about these Terms, please contact us:",
        email: "support@sakura-ai.app",
      },
    ],
  },
  zh: {
    title: "服务条款",
    lastModified: "最后修改：2025年3月17日",
    intro: `请在使用 Sakura AI（"服务"）之前，仔细阅读本服务条款（"条款"）。本服务由 Sakura AI（"公司"、"我们"或"我方"）运营。您访问或使用本服务即表示您同意受本条款的约束。`,
    sections: [
      {
        title: "1. 定义",
        items: [
          { label: "服务", text: "Sakura AI 网站和 API。" },
          { label: "用户/您", text: "访问或使用本服务的任何个人或实体。" },
          { label: "账户", text: "为您创建的用于访问本服务的唯一账户。" },
          { label: "积分", text: "服务内用于生成图像的虚拟货币。每次图像生成消耗 50 积分，免费用户每天获得 100 积分。" },
          { label: "内容", text: "您提交给服务的文本提示词、图像或其他材料。" },
          { label: "隐私政策", text: "我们的隐私政策，可在 /privacy 查阅。" },
          { label: "条款", text: "本服务条款，可在 /terms 查阅。" },
        ],
      },
      {
        title: "2. 账户",
        text: "要使用本服务的某些功能，您必须使用 Google 账户登录。您有责任维护账户的保密性，并对账户下发生的所有活动负责。您同意在发现任何未经授权使用您账户的情况时立即通知我们。我们保留自行决定终止账户、拒绝服务或删除内容的权利。",
      },
      {
        title: "3. 技术要求",
        intro: "要使用本服务，您的设备必须：",
        items: [
          "支持以下浏览器之一：Chrome、Opera、Firefox、Safari 或 Microsoft Edge（建议使用最新稳定版本）。",
          "已启用 JavaScript。",
          "具有稳定的互联网连接。",
        ],
      },
      {
        title: "4. 积分与计费",
        subsections: [
          { title: "4.1 免费积分", text: "每位注册用户每天获得 100 个免费积分，在 UTC 午夜重置。未使用的免费积分不会结转到次日。" },
          { title: "4.2 付费积分", text: "您可以通过 PayPal 购买额外积分。付费积分不会过期，在免费积分耗尽后使用。除适用法律另有规定外，所有购买均不可退款。" },
          { title: "4.3 支付", text: "支付由 PayPal 处理。您必须提供准确完整的账单信息。提交支付信息即表示您授权我们收取相应费用。我们保留以任何理由（包括服务可用性、定价错误或疑似欺诈）拒绝或取消订单的权利。" },
          { title: "4.4 税费", text: "公司不对您所在国家相关机构征收的任何额外费用或税款负责。此类费用的支付由您自行承担。" },
        ],
      },
      {
        title: "5. 可接受使用",
        intro: "您同意不使用本服务：",
        items: [
          "生成违法、有害、威胁性、辱骂性或诽谤性内容。",
          "生成涉及未成年人的色情内容。",
          "侵犯第三方的任何知识产权。",
          "尝试对 API 进行逆向工程、爬取或滥用。",
          "规避速率限制或积分系统。",
          "将本服务用于任何违法目的。",
        ],
        outro: "如果您违反这些规则，我们保留暂停或终止您访问权限的权利。",
      },
      {
        title: "6. 内容",
        text: "您保留提交给本服务的任何内容的所有权。通过提交内容，您授予我们有限的、非独家的、免版税的许可，仅用于提供服务目的处理和传输您的内容。\n\n您声明并保证：(i) 您拥有或有权使用您提交的内容，(ii) 您的内容不侵犯任何人或实体的隐私权、公开权、版权或任何其他权利。\n\n对于您或任何第三方通过本服务提交的内容，我们不承担任何责任。",
      },
      {
        title: "7. AI 生成图像",
        text: "本服务生成的图像由第三方 AI 模型（目前为通过 OpenRouter 的 Google Gemini）生成。我们不保证生成图像的准确性、质量或对任何特定用途的适用性。\n\nAI 生成图像的所有权和许可因司法管辖区而异。您独自负责确保您对生成图像的使用符合适用法律。",
      },
      {
        title: "8. 知识产权",
        text: "本服务及其原创内容（不包括用户提交的内容）、功能和特性是并将继续是 Sakura AI 及其许可方的专有财产。未经我们事先书面同意，不得将我们的商标用于任何产品或服务。",
      },
      {
        title: "9. 免责声明",
        text: '本服务按"现状"和"可用"基础提供，不附带任何明示或暗示的保证，包括但不限于适销性、特定用途适用性或不侵权的暗示保证。我们不保证本服务不会中断、无错误或不含病毒或其他有害组件。',
      },
      {
        title: "10. 责任限制",
        text: "在适用法律允许的最大范围内，Sakura AI 及其董事、员工、合作伙伴、代理商、供应商或关联公司在任何情况下均不对任何间接、附带、特殊、后果性或惩罚性损害承担责任，包括但不限于利润损失、数据损失、商誉损失或其他无形损失，无论这些损害是否由您访问或使用（或无法访问或使用）本服务引起。",
      },
      {
        title: "11. 终止",
        text: "我们可能以任何理由（包括您违反本条款）立即终止或暂停您的账户和对本服务的访问，无需事先通知或承担责任。终止后，您使用本服务的权利将立即停止。因违规被终止时，未使用的付费积分不予退款。",
      },
      {
        title: "12. 适用法律",
        text: "本条款应依据适用法律进行管辖和解释，不考虑其法律冲突条款。因本条款引起的任何争议应通过有约束力的仲裁或在有管辖权的法院解决。",
      },
      {
        title: "13. 条款变更",
        text: '我们保留随时修改或替换本条款的权利。我们将通过更新"最后修改"日期来通知重大变更。您在任何变更后继续使用本服务即表示您接受新条款。',
      },
      {
        title: "14. 联系我们",
        intro: "如果您对本条款有任何疑问，请联系我们：",
        email: "support@sakura-ai.app",
      },
    ],
  },
}

export default function TermsPage() {
  const { locale } = useI18n()
  const c = content[locale]

  return (
    <main className="max-w-3xl mx-auto px-6 py-16 text-sm leading-relaxed">
      <h1 className="text-3xl font-bold mb-2">{c.title}</h1>
      <p className="text-muted-foreground mb-10">{c.lastModified}</p>
      <p className="mb-6">{c.intro}</p>

      {c.sections.map((section) => (
        <section key={section.title} className="mb-8">
          <h2 className="text-xl font-semibold mb-3">{section.title}</h2>

          {/* Definition list */}
          {"items" in section && section.items && !("subsections" in section) && !("intro" in section) && (
            <ul className="list-disc pl-5 space-y-2">
              {(section.items as { label: string; text: string }[]).map((item) => (
                <li key={item.label}><strong>{item.label}</strong> – {item.text}</li>
              ))}
            </ul>
          )}

          {/* Plain text (possibly multi-paragraph) */}
          {"text" in section && section.text && !("subsections" in section) && (
            <div className="space-y-3">
              {(section.text as string).split("\n\n").map((para, i) => (
                <p key={i}>{para}</p>
              ))}
            </div>
          )}

          {/* Subsections (billing) */}
          {"subsections" in section && section.subsections && (
            <div className="space-y-4">
              {section.subsections.map((sub) => (
                <div key={sub.title}>
                  <h3 className="font-medium mb-2">{sub.title}</h3>
                  <p>{sub.text}</p>
                </div>
              ))}
            </div>
          )}

          {/* Intro + list + outro (acceptable use, tech requirements) */}
          {"intro" in section && section.intro && (
            <>
              <p className="mb-3">{section.intro}</p>
              {"items" in section && Array.isArray(section.items) && (
                <ul className="list-disc pl-5 space-y-1">
                  {(section.items as string[]).map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              )}
              {"outro" in section && section.outro && <p className="mt-3">{section.outro}</p>}
              {"email" in section && section.email && (
                <ul className="list-disc pl-5 mt-2">
                  <li>Email: <a href={`mailto:${section.email}`} className="underline">{section.email}</a></li>
                </ul>
              )}
            </>
          )}
        </section>
      ))}
    </main>
  )
}
